version: 2

formats: all

python:
   version: 3.7
   install:
      - requirements: requirements.txt
      - requirements: docs/requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
   builder: html
   configuration: docs/conf.py
   fail_on_warning: false
